"""
SQLAlchemy-адаптер для Document.

Правило: НИКАКИХ session.commit() здесь — только flush() для получения
autogenerated значений (id, created_at) до коммита UoW.

ИЗМЕНЕНИЯ:
- update_status принимает DocumentStatusVO вместо ORM-enum DocumentStatus.
- list_analyzable_for_project использует DocumentStatusVO.
- ORM-enum импортируется отложенно (локальный импорт) — домен не зависит от инфры.
- get_stats_for_project реализован: один SQL-запрос вместо нескольких count().
"""
from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import func, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.interfaces.repositories import IDocumentRepository
from app.domain.value_objects import DocumentStatusVO, PaginationParams

if TYPE_CHECKING:
    from app.infrastructure.db.models.document import Document


def _status_to_orm(vo: DocumentStatusVO):
    from app.infrastructure.db.models.enums import DocumentStatus
    return DocumentStatus(vo.value)


class DocumentRepository(IDocumentRepository):
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    async def get_by_id(self, document_id: uuid.UUID) -> Document | None:
        from app.infrastructure.db.models.document import Document as M
        return await self._session.get(M, document_id)

    async def list_for_project(
        self,
        project_id: uuid.UUID,
        pagination: PaginationParams,
    ) -> list[Document]:
        from app.infrastructure.db.models.document import Document as M
        result = await self._session.execute(
            select(M)
            .where(M.project_id == project_id)
            .order_by(M.created_at.desc())
            .limit(pagination.limit)
            .offset(pagination.offset)
        )
        return list(result.scalars().all())

    async def count_for_project(self, project_id: uuid.UUID) -> int:
        from app.infrastructure.db.models.document import Document as M
        result = await self._session.execute(
            select(func.count())
            .select_from(M)
            .where(M.project_id == project_id)
        )
        return result.scalar_one()

    async def list_analyzable_for_project(
        self,
        project_id: uuid.UUID,
    ) -> list[Document]:
        from app.infrastructure.db.models.document import Document as M
        from app.infrastructure.db.models.enums import DocumentStatus
        analyzable = (
            DocumentStatus.DRAFT,
            DocumentStatus.AWAITING_APPROVAL,
        )
        result = await self._session.execute(
            select(M).where(
                M.project_id == project_id,
                M.status.in_(analyzable),
            )
        )
        return list(result.scalars().all())

    async def get_stats_for_project(
        self,
        project_id: uuid.UUID,
    ) -> dict[str, int]:
        """
        Один SQL-запрос: COUNT(*) FILTER(WHERE status = ?) для каждого статуса.
        Устраняет N+1 round-trips, которые были в предыдущей реализации.
        """
        from app.infrastructure.db.models.document import Document as M
        from app.infrastructure.db.models.enums import DocumentStatus

        rows = await self._session.execute(
            select(
                func.count().filter(M.status == DocumentStatus.DRAFT).label("draft"),
                func.count().filter(M.status == DocumentStatus.IN_PROGRESS).label("in_progress"),
                func.count().filter(M.status == DocumentStatus.AWAITING_APPROVAL).label("awaiting_approval"),
                func.count().filter(M.status == DocumentStatus.APPROVED).label("approved"),
                func.count().filter(M.status == DocumentStatus.REJECTED).label("rejected"),
                func.count().label("total"),
            ).where(M.project_id == project_id)
        )
        row = rows.one()
        return {
            "draft": row.draft,
            "in_progress": row.in_progress,
            "awaiting_approval": row.awaiting_approval,
            "approved": row.approved,
            "rejected": row.rejected,
            "total": row.total,
        }

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    async def update_status(
        self,
        document: Document,
        status: DocumentStatusVO,
    ) -> Document:
        document.status = _status_to_orm(status)
        await self._session.flush()
        await self._session.refresh(document)
        return document

    async def compare_and_increment_review_version(
        self,
        document_id: uuid.UUID,
        expected_version: int,
    ) -> Document | None:
        """CAS: обновляет review_version только если текущая == expected_version.
        Возвращает обновлённый Document или None при конфликте.
        """
        from app.infrastructure.db.models.document import Document as M
        stmt = (
            update(M)
            .where(
                M.id == document_id,
                M.review_version == expected_version,
            )
            .values(review_version=M.review_version + 1)
            .returning(M)
        )
        result = await self._session.execute(stmt)
        updated = result.scalar_one_or_none()
        if updated is None:
            return None
        await self._session.flush()
        return updated
