"""
SQLAlchemy-адаптер для Document.

Правило: НИКАКИХ session.commit() здесь — только flush() для получения
autogenerated значений (id, created_at) до коммита UoW.
"""
import uuid

from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.interfaces.repositories import IDocumentRepository
from app.infrastructure.db.models.document import Document
from app.infrastructure.db.models.enums import DocumentStatus


class DocumentRepository(IDocumentRepository):
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    async def get_by_id(self, document_id: uuid.UUID) -> Document | None:
        return await self._session.get(Document, document_id)

    async def list_for_project(
        self, project_id: uuid.UUID, limit: int, offset: int
    ) -> list[Document]:
        result = await self._session.execute(
            select(Document)
            .where(Document.project_id == project_id)
            .order_by(Document.created_at.desc())
            .limit(limit)
            .offset(offset)
        )
        return list(result.scalars().all())

    async def count_for_project(self, project_id: uuid.UUID) -> int:
        from sqlalchemy import func
        result = await self._session.execute(
            select(func.count())
            .select_from(Document)
            .where(Document.project_id == project_id)
        )
        return result.scalar_one()

    async def list_analyzable_for_project(
        self, project_id: uuid.UUID
    ) -> list[Document]:
        result = await self._session.execute(
            select(Document).where(
                Document.project_id == project_id,
                Document.status.in_(
                    (DocumentStatus.DRAFT, DocumentStatus.AWAITING_APPROVAL)
                ),
            )
        )
        return list(result.scalars().all())

    async def update_status(
        self, document: Document, status: DocumentStatus
    ) -> Document:
        document.status = status
        await self._session.flush()
        await self._session.refresh(document)
        return document

    async def compare_and_increment_review_version(
        self, document_id: uuid.UUID, expected_version: int
    ) -> Document | None:
        """CAS: обновляет review_version только если текущая == expected_version.
        Возвращает обновлённый Document или None при конфликте.
        """
        stmt = (
            update(Document)
            .where(
                Document.id == document_id,
                Document.review_version == expected_version,
            )
            .values(review_version=Document.review_version + 1)
            .returning(Document)
        )
        result = await self._session.execute(stmt)
        updated = result.scalar_one_or_none()
        if updated is None:
            return None
        await self._session.flush()
        return updated
