"""
SQLAlchemy-адаптер для Document.

Правило: НИКАКИХ session.commit() здесь — только flush() для получения
autogenerated значений (id, created_at) до коммита UoW.

ИЗМЕНЕНИЯ:
- update_status принимает DocumentStatusVO вместо ORM-enum DocumentStatus.
- list_analyzable_for_project: статусы передаются через
  _ANALYZABLE_STATUSES (frozenset[DocumentStatusVO]) и конвертируются _status_to_orm.
  DDD-инвариант: репозиторий принимает VO, не знает про ORM-enum на уровне
  публичного интерфейса.
- get_stats_for_project реализован: один SQL-запрос вместо нескольких count().
- list_for_project переведён на KeysetPage: O(log N) вместо O(N) на OFFSET.
- HIGH-1: добавлены create(), update_exported_key().
- HIGH-2: добавлены list_all_for_user(), delete().
- CRIT-3: get_stats_for_project возвращает dict[str, int] (как и объявлено теперь в интерфейсе).
- HIGH-C: create() — убран session.refresh() после flush(); вызывающий код
  получает свежий инстанс через uow.refresh() если нужно.
- M-A: экранирование спецсимволов LIKE (% и _) в list_all_for_user.
- M-C: get_stats_for_project генерирует запрос динамически по DocumentStatusVO,
  новые статусы попадают автоматически.
- HIGH-NEW-3: удалён session.refresh() из update_status() — лишний SELECT,
  flush() уже применил мутацию в рамках текущей транзакции.
- HIGH-1-FIX: update_exported_key пишет в exported_storage_key, а не storage_key.
  storage_key — ключ исходного загруженного файла; exported_storage_key — ключ
  постобработанного (экспортированного) файла. Разные поля, разная семантика.
- M-1-FIX: убран лишний or_() с одним условием в list_all_for_user;
  поиск ведётся по M.name (ilike напрямую, без обёртки or_()).
  Если в будущем потребуется поиск по нескольким полям — вернуть or_().
- FEAT: list_for_project / count_for_project принимают status: DocumentStatusVO | None
  и добавляют WHERE clause при наличии фильтра.
- BUG-FIX-1: create() передавал title= в M(), но поле ORM называется name.
  Исправлено: параметр переименован в name: str, передаётся как M(name=name, ...).
- BUG-FIX-2: list_all_for_user добавлен параметр outdated: bool;
  при outdated=True добавляется EXISTS-подзапрос по pending suggestions.
- BUG-FIX-3: list_all_for_user возвращает list[dict] с ключами
  document / project_name / suggestions_total / suggestions_pending /
  suggestions_accepted / suggestions_rejected — как ожидает роутер.
"""
from __future__ import annotations

import uuid
from typing import TYPE_CHECKING, Any

from sqlalchemy import exists, func, select, tuple_, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.domain.interfaces.repositories import IDocumentRepository
from app.domain.value_objects import DocumentStatusVO, KeysetPage, PaginationParams

if TYPE_CHECKING:
    from app.infrastructure.db.models.document import Document
    from app.infrastructure.db.models.enums import DocumentFormat

# Статусы документа, для которых разрешён запуск анализа.
_ANALYZABLE_STATUSES: frozenset[DocumentStatusVO] = frozenset({
    DocumentStatusVO.DRAFT,
    DocumentStatusVO.AWAITING_APPROVAL,
})

# Допустимые поля сортировки list_all_for_user — защита от SQL-injection.
_SORT_COLUMNS = frozenset({"created_at", "updated_at", "name"})


def _status_to_orm(vo: DocumentStatusVO):
    from app.infrastructure.db.models.enums import DocumentStatus
    return DocumentStatus(vo.value)


class DocumentRepository(IDocumentRepository):
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    # ------------------------------------------------------------------
    # Write: factory
    # ------------------------------------------------------------------

    async def create(
        self,
        *,
        id: uuid.UUID,
        project_id: uuid.UUID,
        name: str,
        format: "DocumentFormat",
        storage_key: str,
    ) -> "Document":
        """Фабричный метод: сервис передаёт параметры, репозиторий строит ORM-объект.

        BUG-FIX-1: параметр переименован с title в name — соответствует ORM-полю.
        HIGH-C: session.refresh() убран — flush() достаточен для получения
        autogenerated-значений (id, created_at). Commit — ответственность UoW.
        """
        from app.infrastructure.db.models.document import Document as M
        from app.infrastructure.db.models.enums import DocumentStatus
        doc = M(
            id=id,
            project_id=project_id,
            name=name,
            format=format,
            storage_key=storage_key,
            status=DocumentStatus.DRAFT,
        )
        self._session.add(doc)
        await self._session.flush()
        return doc

    # ------------------------------------------------------------------
    # Read
    # ------------------------------------------------------------------

    async def get_by_id(self, document_id: uuid.UUID) -> "Document | None":
        from app.infrastructure.db.models.document import Document as M
        return await self._session.get(M, document_id)

    async def list_for_project(
        self,
        project_id: uuid.UUID,
        pagination: KeysetPage | PaginationParams,
        *,
        status: DocumentStatusVO | None = None,
    ) -> list["Document"]:
        """Постраничный список документов проекта.

        Принимает KeysetPage (предпочтительно) или PaginationParams (legacy).
        KeysetPage использует составной индекс ix_documents_project_created_at_id
        → O(log N) на любой странице.
        PaginationParams оставлен для обратной совместимости: работает через
        OFFSET, деградирует линейно на больших таблицах.
        status — опциональный фильтр; при None возвращаются все статусы.
        """
        from app.infrastructure.db.models.document import Document as M

        q = (
            select(M)
            .where(M.project_id == project_id)
            .order_by(M.created_at.desc(), M.id.desc())
            .limit(pagination.limit)
        )

        if status is not None:
            q = q.where(M.status == _status_to_orm(status))

        if isinstance(pagination, KeysetPage) and pagination.has_cursor:
            q = q.where(
                tuple_(M.created_at, M.id)
                < tuple_(pagination.before_created_at, pagination.before_id)
            )
        elif isinstance(pagination, PaginationParams):
            q = q.offset(pagination.offset)

        result = await self._session.execute(q)
        return list(result.scalars().all())

    async def count_for_project(
        self,
        project_id: uuid.UUID,
        *,
        status: DocumentStatusVO | None = None,
    ) -> int:
        """Количество документов в проекте.

        status — опциональный фильтр; при None считаются все статусы.
        """
        from app.infrastructure.db.models.document import Document as M
        q = (
            select(func.count())
            .select_from(M)
            .where(M.project_id == project_id)
        )
        if status is not None:
            q = q.where(M.status == _status_to_orm(status))
        result = await self._session.execute(q)
        return result.scalar_one()

    async def list_analyzable_for_project(
        self,
        project_id: uuid.UUID,
    ) -> list["Document"]:
        from app.infrastructure.db.models.document import Document as M
        analyzable_orm = tuple(_status_to_orm(s) for s in _ANALYZABLE_STATUSES)
        result = await self._session.execute(
            select(M).where(
                M.project_id == project_id,
                M.status.in_(analyzable_orm),
            )
        )
        return list(result.scalars().all())

    async def get_stats_for_project(
        self,
        project_id: uuid.UUID,
    ) -> dict[str, int]:
        """
        M-C: генерирует COUNT(…) FILTER динамически по всем значениям DocumentStatusVO.
        Новый статус, добавленный в VO, автоматически появится в ответе.
        CRIT-3: возвращает dict[str, int].
        """
        from app.infrastructure.db.models.document import Document as M

        stat_cols = [
            func.count().filter(M.status == _status_to_orm(vo)).label(vo.value)
            for vo in DocumentStatusVO
        ]
        stat_cols.append(func.count().label("total"))

        rows = await self._session.execute(
            select(*stat_cols).where(M.project_id == project_id)
        )
        row = rows.one()
        result: dict[str, int] = {vo.value: getattr(row, vo.value) for vo in DocumentStatusVO}
        result["total"] = row.total
        return result

    async def list_all_for_user(
        self,
        user_id: uuid.UUID,
        limit: int,
        offset: int,
        status: DocumentStatusVO | None = None,
        outdated: bool = False,
        search: str | None = None,
        sort_by: str = "updated_at",
        sort_dir: str = "desc",
    ) -> tuple[list[dict[str, Any]], int]:
        """Список документов пользователя с фильтрацией, поиском и сортировкой.

        BUG-FIX-2: добавлен параметр outdated; при True фильтрует документы
        у которых есть хотя бы одна правка со статусом pending.
        BUG-FIX-3: возвращает list[dict] с ключами:
          document, project_name,
          suggestions_total, suggestions_pending,
          suggestions_accepted, suggestions_rejected.
        sort_by валидируется против _SORT_COLUMNS — защита от SQL injection.
        M-A: спецсимволы LIKE (% и _) в search экранируются.
        """
        from app.infrastructure.db.models.analysis_job import AnalysisJob as AJ
        from app.infrastructure.db.models.document import Document as M
        from app.infrastructure.db.models.enums import SuggestionStatus
        from app.infrastructure.db.models.project import Project as P
        from app.infrastructure.db.models.suggestion import Suggestion as S

        if sort_by not in _SORT_COLUMNS:
            sort_by = "updated_at"

        # Агрегированные счётчики правок через LEFT JOIN + COUNT FILTER
        suggestions_total = (
            func.count(S.id)
            .filter(AJ.document_id == M.id)
            .label("suggestions_total")
        )
        suggestions_pending = (
            func.count(S.id)
            .filter(AJ.document_id == M.id, S.status == SuggestionStatus.PENDING)
            .label("suggestions_pending")
        )
        suggestions_accepted = (
            func.count(S.id)
            .filter(AJ.document_id == M.id, S.status == SuggestionStatus.ACCEPTED)
            .label("suggestions_accepted")
        )
        suggestions_rejected = (
            func.count(S.id)
            .filter(AJ.document_id == M.id, S.status == SuggestionStatus.REJECTED)
            .label("suggestions_rejected")
        )

        base_q = (
            select(
                M,
                P.name.label("project_name"),
                suggestions_total,
                suggestions_pending,
                suggestions_accepted,
                suggestions_rejected,
            )
            .join(P, M.project_id == P.id)
            .outerjoin(AJ, AJ.document_id == M.id)
            .outerjoin(S, S.analysis_job_id == AJ.id)
            .where(P.owner_id == user_id)
            .group_by(M.id, P.name)
        )

        if status is not None:
            base_q = base_q.where(M.status == _status_to_orm(status))

        if outdated:
            # EXISTS (pending suggestion для этого документа)
            pending_exists = exists(
                select(S.id)
                .join(AJ, S.analysis_job_id == AJ.id)
                .where(
                    AJ.document_id == M.id,
                    S.status == SuggestionStatus.PENDING,
                )
            )
            base_q = base_q.where(pending_exists)

        if search:
            safe_search = search.replace("\\", "\\\\").replace("%", "\\%").replace("_", "\\_")
            base_q = base_q.where(M.name.ilike(f"%{safe_search}%", escape="\\"))

        # Сортировка
        sort_col = getattr(M, sort_by)
        order_expr = sort_col.asc() if sort_dir == "asc" else sort_col.desc()
        items_q = base_q.order_by(order_expr, M.id.desc()).limit(limit).offset(offset)

        # COUNT через subquery (группировка сохраняется)
        count_q = select(func.count()).select_from(base_q.subquery())

        items_result = await self._session.execute(items_q)
        count_result = await self._session.execute(count_q)

        rows = items_result.all()
        items: list[dict[str, Any]] = [
            {
                "document": row.Document,
                "project_name": row.project_name,
                "suggestions_total": row.suggestions_total,
                "suggestions_pending": row.suggestions_pending,
                "suggestions_accepted": row.suggestions_accepted,
                "suggestions_rejected": row.suggestions_rejected,
            }
            for row in rows
        ]
        return items, count_result.scalar_one()

    # ------------------------------------------------------------------
    # Write
    # ------------------------------------------------------------------

    async def update_status(
        self,
        document: "Document",
        status: DocumentStatusVO,
    ) -> "Document":
        """HIGH-NEW-3: удалён session.refresh() — flush() достаточен.

        refresh() после flush() выполняет лишний SELECT и может перезаписать
        другие dirty-атрибуты объекта в сессии. ORM-объект уже актуален
        в рамках текущей транзакции без round-trip.
        """
        document.status = _status_to_orm(status)
        await self._session.flush()
        return document

    async def update_exported_key(
        self,
        document: "Document",
        export_key: str,
    ) -> None:
        """HIGH-1-FIX: сохранить ключ экспортированного файла в exported_storage_key.

        storage_key — ключ исходного загруженного файла (неизменяем после upload).
        exported_storage_key — ключ финального постобработанного файла.
        Запись в storage_key была бы ошибкой: она затёрла бы ссылку на оригинал
        и сломала бы get_download_url() / get_original_content().
        """
        document.exported_storage_key = export_key
        await self._session.flush()

    async def compare_and_increment_review_version(
        self,
        document_id: uuid.UUID,
        expected_version: int,
    ) -> "Document | None":
        """CAS: обновляет review_version только если текущая == expected_version."""
        from app.infrastructure.db.models.document import Document as M
        stmt = (
            update(M)
            .where(
                M.id == document_id,
                M.review_version == expected_version,
            )
            .values(review_version=M.review_version + 1)
            .returning(M)
        )
        result = await self._session.execute(stmt)
        updated = result.scalar_one_or_none()
        if updated is None:
            return None
        await self._session.flush()
        return updated

    async def delete(self, document: "Document") -> None:
        """HIGH-2: удалить запись документа. ON DELETE CASCADE убирает связанные строки."""
        await self._session.delete(document)
        await self._session.flush()
